#if !canImport(ObjectiveC)
  import XCTest

  extension SappiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SappiTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(SappiTests.__allTests__SappiTests)
    ]
  }
#endif
